#어플리케이션 포트 -> 디폴트가 8080
  server:
    port: 8080

# database 연동 설정
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webboard_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ms_user
      password: 1234

  # mybatis
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml